name: validate maxplayers after the workflow finishes holy fuck why

on:
  workflow_run:
    workflows: ["validate syncrange"]
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write    
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "<MaxPlayers>16</MaxPlayers>"
          replace: "<MaxPlayers>32</MaxPlayers>"
          include: "**.sbc"
          regex: true
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4        