name: Aristeas NewUniversalUpload
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - stable

jobs:
  UploadMods:
    if: github.repository_owner == 'StarCoreSE' || github.repository_owner == 'ari-steas'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4.1.4
        with:
          fetch-depth: 0
        
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
            separator: ','
      
      #- name: List all changed files
      #  env:
      #    ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      #  run: |
      #    for file in ${ALL_CHANGED_FILES}; do
      #      echo "$file was changed"
      #    done
      - id: test_SEWT
        run: |
          & "C:\Program Files\SCUniversalUpload\SC_NewUniversalUpload.exe" --repo "${{ github.workspace }}" --changes "${{ steps.changed-files.outputs.all_changed_and_modified_files }}" --changelog "${{ github.event.head_commit.message }}"
          
      - uses: EndBug/add-and-commit@v9
